version: '3.3'

services:
  server:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - timezone-db
  database:
    image: postgres:14.1
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}