extend type Query {
	getUsers: [User]!
	getUser(id: Int!): User!
	getTimezones(user_id: Int!): [Timezone]!
}

extend type Mutation {
	updateUser(id: Int!, role: String!): User!
	createUser(email: String!, password: String!, password_confirmation: String!): User!
	deleteUser(id: Int!): User!
	createTimezone(user_id: Int!, name: String!, city: String!, country: String): Timezone!
	updateTimezone(user_id: Int!, id: Int!, data: UpdateTimezoneData!): Timezone!
	deleteTimezone(id: Int!): Timezone!
}