scalar Date

extend type Query {
	login(email: String!, password: String!): AuthenticateResponse!
	getUser: User!
}

extend type Mutation {
	signup(email: String!, password: String!, password_confirmation: String!): User!
}

type AuthenticateResponse {
	token: String!
}

type User {
	id: Int!
	email: String!
	role: String!
	created_at: Date!
	updated_at: Date!
}