extend type Query {
	getUser: User!
	getTimezones: [Timezone]!
}

extend type Mutation {
	createTimezone(name: String!, city: String!, country: String): Timezone!
	updateTimezone(id: Int!, data: UpdateTimezoneData): Timezone!
	deleteTimezone(id: Int!): Timezone!
}
